### ISSUE TITLE
Systems -> Drivers -> Show Driver Inheritance 

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#111]
Add a visual indicator to drivers in backoffice if they are added as an existing driver to a system or added as a mutually exclusive driver to that system. Perhaps the little network arrows back and forth to show its inherited from another system?

**Comment by MrYuion** [comment]
@jeremyw24 I'm not sure this is possible. Drivers aren't directly linked to systems.
For modules the relationship between systems is only well defined for logic drivers. i.e. logic modules must have a system and can only be linked to one system.

**Comment by jeremyw24** [comment]
@MrYuion perhaps we indicate if it is a logic driver or not? that might help distinguish, then we can document this relationship.

**Comment by MrYuion** [comment]
It already does that.![Screen Shot 2022-03-11 at 3.16.44 pm.png](https://images.zenhubusercontent.com/5f9b8db76ee7bb4af403e647/5834cc8c-46ad-4655-ace7-036ea945ff0b)

**Comment by jeremyw24** [comment]
I was proposing it be shown here ![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/b22bab96-7ab9-468e-a199-0002c5552025)

**Comment by MrYuion** [comment]
Added a column for showing the driver type in the table.
