### ISSUE TITLE
ngx-outlook: Create standardised template for Outlook add-in

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#14]
From Jira: https://acaprojects.atlassian.net/browse/PTT-23

ngx-outlook: Create standardised template for Outlook add-in

- Room booking ONLY 
- Login via SSO
- Unbranded (no company logos), with similar style (font,colours, etc) to ngx-staff-app

- Add a Readme.MD with instructions for forkers on how to switch out the manifest file and deploy on to client environments

**Comment by MrYuion** [comment]
For the most part it looks like a normal app but also requires a `manifest.xml` file with the configuration in Outlook.
https://docs.microsoft.com/en-au/office/dev/add-ins/outlook/manifests

Also if we want to talk to outlook from the add-in we will need to include the javascript API in the applicaton.
https://docs.microsoft.com/en-au/office/dev/add-ins/outlook/apis
