### ISSUE TITLE
staff/schedule view event: Body should render HTML not display it

### ISSUE THREAD

**Issue by w-le** [PlaceOS/user-interfaces#142]
[APP][APP] 9ea81ab | Built: 18th May 2022, 2:26PM

<img width="711" alt="Screen Shot 2022-06-02 at 5 18 22 pm" src="https://user-images.githubusercontent.com/10395560/171558006-a4fd6c2f-f91d-4492-bfa5-7735ce25a70f.png">

**Comment by jeremyw24** [comment]
fixed in https://github.com/PlaceOS/user-interfaces/commit/4508cb5d10baca9d1e2e206830414b78d1c3ccbf
