### ISSUE TITLE
WPA: Meetings to show up in Amber colour

### ISSUE THREAD

**Issue by juliejgiles** [PlaceOS/user-interfaces#144]
Verify meetings waiting for approval to show up in amber.
At the moment, meetings waiting for acceptance from an External Attendee change from amber to green colour automatically after a few seconds.

**Comment by MrYuion** [comment]
@jeremyw24, I'm not sure if we have a room available to test this.

**Comment by MrYuion** [comment]
Looks to be working fine.![Screen Shot 2022-06-22 at 11.36.46 am.png](https://images.zenhubusercontent.com/5f9b8db76ee7bb4af403e647/714f7bda-5354-4495-a40a-a9d4a7402bcb)
