### ISSUE TITLE
WPA: Duration of a meeting cannot be extended

### ISSUE THREAD

**Issue by juliejgiles** [PlaceOS/user-interfaces#147]
The following error message is displayed when trying to extend a meeting by 30min although the space is available for that time slot

<img width="672" alt="image" src="https://user-images.githubusercontent.com/69617566/172398568-892fc542-f334-46c4-9a3e-3d485d864d5e.png">

**Comment by stakach** [comment]
This was not working as the `period_start=NaN&period_end=NaN` params are requesting `NaN`

**Comment by MrYuion** [comment]
It should work then on the latest.
