### ISSUE TITLE
WPA: All day booking is not available

### ISSUE THREAD

**Issue by juliejgiles** [PlaceOS/user-interfaces#148]
Maximum duration of booking is 4 hours:

![image.png](https://images.zenhubusercontent.com/6041a04df503415622bcb570/e393b5a1-8766-4f02-962b-6ce884c562e0)

**Comment by jeremyw24** [comment]
Issue due to incorrect app configuration for metadata.
![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/38404588-4c9f-440d-8b5c-1e24dba95330)
