### ISSUE TITLE
WPA: Inconsistent behaviour when booking a meeting with multiple External Attendees

### ISSUE THREAD

**Issue by juliejgiles** [PlaceOS/user-interfaces#149]
Bookings with the same external attendees is rejected instantly on a day, but not on another day:

![image.png](https://images.zenhubusercontent.com/6041a04df503415622bcb570/db6c2254-13c3-4461-8a4d-e150044d9ef4)

**Comment by MrYuion** [comment]
@jeremyw24 I believe this is a backend/calendar issue.
Workplace app has no effect on the declined state of calendar events.
