### ISSUE TITLE
WPA: Map and pins not loading for a selected space

### ISSUE THREAD

**Issue by juliejgiles** [PlaceOS/user-interfaces#150]
![image.png](https://images.zenhubusercontent.com/6041a04df503415622bcb570/d3184f1c-e16b-4f79-91a0-e0e94a476c7a)

**Comment by juliejgiles** [comment]
Issue created as a result of the WPA Regression testing on 7 June 2022. See item #67 in spreadsheet: https://docs.google.com/spreadsheets/d/1ot9-pSdQ-K3j2cojNTxbVZ_EvAn3tHcfbAfDU4-e4Pk/edit#gid=0

**Comment by MrYuion** [comment]
Seems to be working fine.
Please make sure that all the data is correct if you see this again.
The room should link to a level zone with a map URL and the room should have a `map_id` that maps to an element on the SVG that the URL links to.
