### ISSUE TITLE
Display Signs of Life

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#157]
Vergesense now exposes signs_of_life value as bool from the areamanger driver.

We need to add a status to the map, where vergesense is installed that will indicate a fourth status that there is signs of life but is NOT occupied.

For example:
green available/not occupied
amber tenative/booked/not occupied/not checked in
red booked/occupied/checked in
blue signs of life detected but no human

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/a7eebb93-2720-497d-9730-ab786044e9cc)

**Comment by MrYuion** [comment]
@jeremyw24, should be good to test.

**Comment by jeremyw24** [comment]
@MrYuion can you add a legend to the spaces page - I thought we had one but its not there. Just clearly defining what the colours are.

**Comment by MrYuion** [comment]
@jeremyw24, that should be up.
