### ISSUE TITLE
If there is no map, display message

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#162]
When a level has assets but no map i.e. desks, instead of the spinning wheel can we display a message 'This floor does not have a map loaded.'

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/fa95bc83-8b3a-4e35-9555-d52b5daed141)

**Comment by MrYuion** [comment]
@jeremyw24, latest version should now show `No map` when URL is not set.
