### ISSUE TITLE
WPA Include Checkout Screen (Stripe Integration)

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#166]
Objective: Enable a checkout process that will enable users to book a desk/room/car park and pay for the booking online via credit card or create a transaction record in stripe to later be paid on-site with a physical stripe terminal.

Propose we introduce a new screen after the select desk/room/car park workflow to allow this to be seamlessly dropped into the new or old WPA interface. 

The checkout screen shall show the booking overview and total cost payable, allowing the user to enter credit card details to pay online (similar to towers). With option to email receipt. 

Payment feature shall be able to be enabled/disabled via WPA metadata properties and applied to each booking flow individually. 

Payment data shall be stored against booking metadata including stripe reference, transaction state, amount.

**Comment by MrYuion** [comment]
@jeremyw24 is the stripe driver setup somewhere for me to test this?

**Comment by MrYuion** [comment]
Driver doesn't seem to handle managing the customer details.

**Comment by MrYuion** [comment]
Getting 500 error trying to get product prices.
