### ISSUE TITLE
Validate and Test WPA Uplift

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#173]
https://templates.demo.place.tech/workplace/#/landing
https://templates.demo.place.tech/workplace/#/your-bookings
https://templates.demo.place.tech/workplace/#/book/meeting/form
https://templates.demo.place.tech/workplace/#/book/newdesk/form
https://templates.demo.place.tech/workplace/#/book/visitor/form

**Comment by juliejgiles** [comment]
test results: https://drive.google.com/drive/u/1/folders/174ZDdOR_epZVZ1yh5tj8DDnrQNROHAix
