### ISSUE TITLE
Allow customisation if data shown on location services modal

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#177]
When location services is enabled, we need to be able to select what information is shown on the location modal.

At present it seems to display all known information, but would be good to be able to dynamically set this to just show users name for example and exclude MAC address etc.

**Comment by MrYuion** [comment]
@jeremyw24, is this the zone information or device tooltips/popups?

**Comment by jeremyw24** [comment]
@MrYuion the device tooltips and popus.

**Comment by MrYuion** [comment]
Added setting `app.explore.hide_device_fields` for this.
Takes an array of strings which refer to the fields to hide.
Options are `manufacturer`, `os`, `ssid`, `username` and `user`.
e.g. `["os", "ssid"]` would hide the device OS and access point SSID.
