### ISSUE TITLE
Change logic for Booking approval status display.

### ISSUE THREAD

**Issue by w-le** [PlaceOS/user-interfaces#178]
See https://github.com/PlaceOS/staff-api/issues/205

Originally raised as a staff-api change request, comment thread there states that this should instead be done as a frontend change instead.

**Comment by MrYuion** [comment]
Frontend already does this.
https://github.com/PlaceOS/user-interfaces/blob/b333879d29258e21e4abd07e3f3492d779329f29/libs/bookings/src/lib/booking.class.ts#L130
