### ISSUE TITLE
Concierge -> Commence build of UI with Mocks

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#186]

**Comment by juliejgiles** [comment]
Build UI components:
- [x] drag and drop container for questions
- [x] question bank container
- [x] `Design` and `Preview` tabs
- [x] reusable input field
- [x] text question component
- [x] ratings question component
- [x] search-bar UI
- [x] reusable buttons with icons
- [ ] comment question component
- [ ] checkbox question component
- [ ] dropdown question component

**Comment by juliejgiles** [comment]
Build UI components:
- [x] drag and drop container for questions
- [x] question bank container
- [x] `Design` and `Preview` tabs
- [x] reusable input field
- [x] text question component
- [x] ratings question component
- [x] search-bar UI
- [x] reusable buttons with icons
- [x] comment question component
- [x] checkbox question component
- [x] dropdown question component
