### ISSUE TITLE
Concierge -> Catering Item in order not showing name

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#197]
When catering is requested for a meeting, it displays correctly the information in “Today’s Orders” section but instead of listing the name of the catering item ordered, it shows order code.

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/b1645fcf-a531-4384-af4c-d3a24c60eca0)

**Comment by MrYuion** [comment]
Should be fixed in the latest dev build.
