### ISSUE TITLE
WPA -> Currency should localise

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#198]
Currency should show the correct currency symbol in WPA based on locale. 

Even though in backoffice the currency is set to be “GBP” (British Pound), in workplace app I still see USD. Can we please change it to be GBP £?

**Comment by MrYuion** [comment]
@jeremyw24 I've properly hooked up the `app.currency` setting to all the instances of pricing I could find.
The value should be an ISO currency code.
