### ISSUE TITLE
WPA -> Intuitively suggest areas to book based on users history

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#200]
Refer to PRD: https://acaprojects.atlassian.net/jira/polaris/projects/PP/ideas/view/949483?selectedIssue=PP-61&issueViewSection=overview&atlOrigin=eyJpIjoiMWJhMjRiZWYzMzQzNGViZDgyNTM2YjRmODZiYzhiZTAiLCJwIjoiaiJ9

## Objective
Recommend desks and rooms based on users previous bookings and allow users to book these frequent spaces with minimal effort. 

## User Story & Relevant Background
Users would like a method to be provided intuitively with recommended spaces to book based on their booking history and/or frequented locations within a building.

## Assumptions
We would like to present users with frequently booked spaces rather than recently booked spaces.

Potentially process and store this data on the backend and provide endpoint for frontend to get an array of the recommendations.

**Comment by jeremyw24** [comment]
@MrYuion suggest we change 'Favourites' display on the landing page to 'Favourites & Recent' or similar rather than adding another field for simplicity?

**Comment by MrYuion** [comment]
@jeremyw24 I'm fine with that though we though we don't have too much space for adding extra words to the tab.
Another place we could add it is in the "Available Now" section, having it only show when recently booked spaces are actually available at the current time.

**Comment by MrYuion** [comment]
I think Candy made a design for this but I can't find it.
