### ISSUE TITLE
concierge/reports/spaces: cannot read any data in table

### ISSUE THREAD

**Issue by w-le** [PlaceOS/user-interfaces#205]
major CSS issue in `42be1a8 | Built: 12th Oct 2022, 10:12AM`

<img width="1991" alt="Screen Shot 2022-10-14 at 2 36 51 pm" src="https://user-images.githubusercontent.com/10395560/195779325-21edef1b-ac63-4ebf-94be-81fa4f231cab.png">

**Comment by MrYuion** [comment]
Just missing some dark mode styles. Fixed with commit 1957005
