### ISSUE TITLE
WPA -> My Day -> View Event Overflow Issues

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#208]
Lines overflow outside of the box.

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/269407a8-47b3-4529-a2d0-6fe39e6fdb66)

**Comment by MrYuion** [comment]
Fix pushed

**Comment by jeremyw24** [comment]
@MrYuion better but now the bottom right box is not aligned.
![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/c20e8694-95cf-4513-a8ad-4b18f4bbb800)

**Comment by MrYuion** [comment]
Hmm... It's not meant to be.
