### ISSUE TITLE
WPA -> My Day -> View Event -> Checked In False

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#209]
When viewing a pending event the button says 'Checked In' when I have not checked in yet, assume button should say checkin.

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/33a83fa3-d242-4b28-aa18-ca89d5b3b119)

**Comment by MrYuion** [comment]
Hmm... we don't really have this ability at the API level so I hadn't hooked it up to anything.
