### ISSUE TITLE
WPA -> My Day -> Guest RSVP not shown

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#216]
The guest RSVP state is not updated in the Attendees modal when inspecting a booking.

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/448ca386-e821-4512-8fea-381841744298)
![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/1f64e735-7d36-4a83-9e84-3f7b5a511ed4)

**Comment by MrYuion** [comment]
Made a fix.
