### ISSUE TITLE
WPA -> Desk/Room Place Holder Icons

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#219]
https://www.figma.com/file/aKmr87twSbsKd2EKTvAgUk/HIFI-WPA-Light-Mode?node-id=2%3A7#303104106

On landing, where a room or desk does not have an uploaded image, it should show the placeholder icons per design:
![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/ac51431a-76f8-4a97-9985-d5b53f29247c)

On the room details page in the room booking workflow, the photo banner should be hidden where there is no photo.
![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/a7eaf18b-b171-4ff1-9197-ff470c9fd010)

On my day, the image banner should be hidden where there is no image uploaded.
![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/7c7cd576-7377-4289-a0a9-5ba9163eef89)

**Comment by jeremyw24** [comment]
@MrYuion something is a bit off in dsk booking, the icon sits aligned to the top and the empty image is still displayed on the right.
![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/3123a122-6e67-4dfb-9a39-466af2e35e2a)

**Comment by jeremyw24** [comment]
Icon is not shown once desk is selected.
![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/e5c4a50e-2ad3-4e3e-8ed5-598baa59ba46)

**Comment by MrYuion** [comment]
@jeremyw24, fixed those last 2 issues
