### ISSUE TITLE
WPA -> Spaces shows Free in Popup When Booked

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#221]
When a space is booked in use or pending, the map shows the correct state but the pop up modal shows free.

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/cd8413c3-3ac2-46f9-912b-ff0353dd6b57)

**Comment by MrYuion** [comment]
Hmm... I can't reproduce this. The tooltip uses the same value from the driver that sets the colour of the room in the SVG.
