### ISSUE TITLE
WPA -> Room Booking -> Catering not Working

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#226]
Zone has catering enabled and a menu but error returns no catering available.
![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/c096dc57-5cfd-4177-a78b-c2b9b53872ba)

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/e9ec492e-969d-45f9-9552-218b4c5e53cb)

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/fbca7a66-fdc4-47ee-8c40-7f9b953ffdce)

**Comment by MrYuion** [comment]
`catering_enabled` should be a zone id rather than a boolean.
If you don't want to restrict catering to a level you can set it to the org or building zone.
