### ISSUE TITLE
WPA -> Adhoc Booking -> Hide Features

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#239]
Hide features that are not enabled for the room i.e. lighting and blinds

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/0c3d4c04-795d-431e-83a7-2cdae5bc6730)

**Comment by MrYuion** [comment]
Hmm... what features should I refer to for showing each of them?
Currently it's just hardcoded to match the design.

**Comment by jeremyw24** [comment]
TV = AV Logic Driver presence?
Catering = Can we get this from zone data for catering enabled zone?
Blinds & Lighting = Blinds/Lighting Driver presence?
