### ISSUE TITLE
WPA -> Landing -> Hide Left Colleagues Bar

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#240]
Add configuration to enable hiding of the left bar that contains favourites/colleagues.

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/fa818ac7-5bf0-449b-ab66-26c571d94266)

**Comment by jeremyw24** [comment]
@MrYuion what is the config to enable/disable this?

**Comment by MrYuion** [comment]
`app.general.hide_colleagues` to remove colleagues.
`app.general.hide_landing_sidebar` to completely remove the sidebar.
