### ISSUE TITLE
WPA -> Landing -> Option to hide Spaces or Rooms

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#241]
Add config to support hiding of spaces or rooms on landing page.

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/fc3b0327-d07e-45bb-8b1a-bee96c3c3884)

**Comment by jeremyw24** [comment]
@MrYuion what is the config to enable/disable this?

**Comment by MrYuion** [comment]
`app.general.hide_spaces` and `app.general.hide_rooms`.
