### ISSUE TITLE
WPA -> Room Booking -> Capacity Filters

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#244]
The room booking capacity filters should only return rooms in the defined capacity range, in this example I have selected 1-2 people, however 8p meeting rooms are shown first.

The room capacity should also update based on number of attendees added to the booking. 

By returning rooms specific to the capacity/attendees we should be able to improve response time and not confuse users by returning 8p meeting rooms for a 2p meeting.

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/7bf26d10-412c-42e1-abeb-4d850daa7db3)

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/3e12e383-2641-4c6b-8159-92a682a43f37)

**Comment by vinnyo** [comment]
Just want to confirm the change:

The current filter assumes that a 2 person party might be interested in larger rooms meant for larger parties (which is viable if there are no smaller rooms available) hence the label `Minimum X people`.

If we go with this change, we're essentially changing the filter to `Max X people` which means that a 2 person party will not see rooms with larger capacity.

**Comment by MrYuion** [comment]
@jeremyw24, do you have an answer for the question raised by @vinnyo ?

**Comment by jeremyw24** [comment]
I think if you set it to 1-2 people it should show all the 1-2 person meeting rooms first, then go on to show larger rooms.

At present its confusing as users enter 1-2 or 3-5 or whatever but the rooms are just in random order. I dont think it matters if it shows larger rooms but it should show rooms within the selected range first.

**Comment by MrYuion** [comment]
While I feel that the logic should match what the UI offers, having a range set by a single UI element is probably not the best UX and complicates the filtering of rooms. 
Did we want to change the UI to allow selecting a min and a max?
Or should we change the labels to match how the logic currently operates?
Also should I be automatically adjusting the selected option based on attendees?

**Comment by jeremyw24** [comment]
change the labels to match how it operates and ensure rooms are listed in order of capacity selected by the user

**Comment by jeremyw24** [comment]
@MrYuion capacity filtering is functional but still shows the incorrect filter in the add room modal.
