### ISSUE TITLE
Booking Panel -> Set Image via Zone Config

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#245]
Currently, the Booking Panel App will display the image associated with the room, if one is uploaded.

Clients want the same image on all booking panels, but different to the room.

Propose we create `booking_panel` metadata in the org or building zones that takes a `background_image` parameter allowing you to specify the image shown on the panel, if no image supplied the panel shall default to black.

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/30d630ab-935b-48a3-bfc3-6946f3e4e745)

**Comment by MrYuion** [comment]
I think this is already possible using a driver setting `room_image`.

**Comment by jeremyw24** [comment]
@MrYuion adding room_image to the booking driver does indeed force an image but breaks the panel layout.
![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/a0924f10-0c9a-4463-8f12-e61e059b7b24)

**Comment by MrYuion** [comment]
Pushed a fix.
It was showing the offline view when then room image was set.
