### ISSUE TITLE
Concierge -> Cant Save Assets

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#250]
Saving assets returns 404.

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/6c1896ef-1de5-4f21-8bd2-e67bd74851b9)

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/938a200b-b7e5-48c2-bf3f-fde9deea2f08)

**Comment by MrYuion** [comment]
@stakach, what's the endpoint for this?

**Comment by jeremyw24** [comment]
https://docs.placeos.com/reference/api/rest-api/assets#api-engine-v2-assets-1

**Comment by jeremyw24** [comment]
@MrYuion this still returns the same error

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/7cc5f6bf-a1d3-41a6-948b-41b9e6dcd490)

**Comment by MrYuion** [comment]
No, that's a different error. Permissions error now, back to the backend side.

**Comment by jeremyw24** [comment]
@MrYuion i am sys admin and still get the same error.

**Comment by MrYuion** [comment]
@stakach, you able to have a look at this?

**Comment by jeremyw24** [comment]
@MrYuion still cant save assets

**Comment by MrYuion** [comment]
Has the backend been updated?
