### ISSUE TITLE
Booking Panel Add Portuguese Translation

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#251]

**Comment by MrYuion** [comment]
Language can be set by adding `?lang=<locale>` to URL.
Translation for Portuguese is here. `?lang=pt`
https://github.com/PlaceOS/user-interfaces/blob/develop/shared/assets/locale/pt.json

**Comment by jeremyw24** [comment]
@MrYuion will it also automatically detect the system language and switch?

**Comment by MrYuion** [comment]
Yeah, as long as there is a translation file.
