### ISSUE TITLE
WPA -> B2C -> Calendar Modal -> Detect Click

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#259]
On the 'add to calendar' modal when booking rooms on the workplace app while in B2C mode, the app should listen for a users click on the 3 calendar buttons, if no click is detected it should warn the user they have not created the event when clicking done.

1. Find room to book in list/map.
2. Modal opens.
3. Listen for user to click on 1 of the 3 options.
4. If no click detected but user clicks done, warn user 'You need to select a calendar option to finish creating this booking'.
5. If click detected and user clicks done, dismiss modal.

**Comment by jeremyw24** [comment]
@MrYuion this does not work. I am still able to close the modal without clicking any of the 3 calendar options.

**Comment by MrYuion** [comment]
Yeah, I just made it so it doesn't act like the booking was completed.
The modal close isn't the easy for me to hook into.
