### ISSUE TITLE
WPA -> Catering -> Allow Catering Notes

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#264]
Catering orders should allow notes to be added to the order which are visible to the caterers on the order dashboard.

The notes field should have configuration that can optionally force the notes field to be required.

## Acceptance Criteria
- Notes field is visible once catering items are added to the order.
- Config exposed by Concierge to enforce the catering notes.
- Catering notes are visible in the order dashboard.

**Comment by jeremyw24** [comment]
@MrYuion catering notes are visible but can not see how to make them required per the requirements above.

**Comment by MrYuion** [comment]
`app.events.catering_notes_required`
