### ISSUE TITLE
WPA -> Catering Items Default Image

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#266]
Catering menu items should show a default image where a custom image is not configured on the menu item.

This icon should match room and desk default icons.

We do not want to see a grey square.

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/f42f1a0f-03ec-4e23-b7da-f9e4456afaaf)

**Comment by MrYuion** [comment]
@jeremyw24 has Candy made an icon for this?
