### ISSUE TITLE
Concierge -> Catering -> Not recording item variation

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#273]
When user selects an item (i.e. water) and an option of the item (i.e. sparkling), when booking is completed the catering order does not seem to pick up the item and option but it still display as the order has both options (still and sparkling water)

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/a335f0fc-6b7c-4051-b137-be72467e542e)

**Comment by jeremyw24** [comment]
@MrYuion no variation is shown now.

**Comment by MrYuion** [comment]
Hmm... Seems to work fine for me on the latest.![Screenshot 2022-12-19 at 4.22.24 pm.png](https://images.zenhubusercontent.com/5f9b8db76ee7bb4af403e647/326d444c-66b7-4079-b87a-4be7d9823c9e)
