### ISSUE TITLE
WPA -> Room Facilities

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#274]
At present, it seems room facilities automatically populates based on modules added to the system, additional items can also be added. So for a bookable room it always shows `Calendar` and `Bookings`.

Removing the system added modules will automatically repopulate them.

1. Do not show `calendar` and `bookings` as features.
2. Show video conference as a facility if a vc module is added to the system.
3. All other features to be user entered.

**Comment by MrYuion** [comment]
@jeremyw24, 2 and 3 don't seem like frontend.
Do note that the features aren't populated by the frontend, you can set them in backoffice but I don't explicitly do anything with setting the value automatically.
I guess 1 could also be handled by whatever is automatically setting the values.

**Comment by jeremyw24** [comment]
moved to jira https://acaprojects.atlassian.net/browse/PPT-81?atlOrigin=eyJpIjoiYmZlMDc3NDMzOGRhNDUxZWIzMGNkZjE3NTZhMTU0NzIiLCJwIjoiaiJ9
