### ISSUE TITLE
WPA -> Desk Checkin QR Codes

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#275]
Ensure scanning a desk checkin QR code yields the correct user experience with necessary and appropriate feedback.

Although it is now checking in properly, the user experience is not correct. It currently shows a toast to say check in successful and a blank page, even if I have not booked the desk. 

## Acceptance Criteria

- If a user scans a desk they have booked at the right date/time they will be shown a successful checkin message, the desk booking will be updated to checked in.
- If a user scans a desk that they have not booked, but the desk is available, the user can ad-hoc book the desk now.
- If a user scans a desk they have not booked, but the desk is booked by another user, the user should be shown a message that they have not booked the desk and it is currently unavailable.

**Comment by jeremyw24** [comment]
@MrYuion i get a fail snack bar then this screen below.

This is not correct.

It should be a full screen error and does not meet the criteria above.

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/1c284544-6252-4890-94d2-e68c5f007259)

**Comment by jeremyw24** [comment]
Failure reports desk is booked to someone else, but it is my booking ![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/47fa3db8-5480-43ef-a863-d6acfd65b750)

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/dd7735b8-96f9-4920-bfbf-af28500debc4)

**Comment by MrYuion** [comment]
@jeremyw24, fixed the user check.
There is a fullscreen view for success.
I don't have an image for a fullscreen error view. 
There will be too much whitespace, it will look a bit weird so I'm just going to leave the errors as toasts.

**Comment by jeremyw24** [comment]
@MrYuion If I scan a QR Code for a desk I do not have booked, but currently have a booking at another desk it just takes me straight to the desk booking form.

It should inform me I have an existing booking at a desk at this time and refer me to the correct desk as I wont be able to book a new desk while I have an existing desk booking at another desk.
