### ISSUE TITLE
WPA (Mobile) -> Rooms -> Map button shows 'no map'

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#282]
In responsive mode when clicking the map toggle, it reports no map is found.

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/24dd7dcf-ba85-4245-931f-fdbc3352face)

**Comment by MrYuion** [comment]
Should be fixed in the build from 1 hour ago.
