### ISSUE TITLE
WPA -> Landing -> Show all bookings in your bookings

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#284]
The your bookings section should show desk and room bookings and direct the user to your day to modify bookings.

**Comment by jeremyw24** [comment]
@MrYuion can we only show bookings in the future for today, not previous bookings?

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/e33ba45b-dacc-4097-8570-0db752ce71a7)

**Comment by MrYuion** [comment]
@jeremyw24 did you want in-progress bookings to show?
