### ISSUE TITLE
WPA -> Spaces -> Can Book Pending Desk

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#292]
Users can click a pending desk and create a booking overlapping the current booking.

See below, I have the desk booked for 1020-1120 but it allows me to book it for 1025.

Expected Behaviour:
- Users should be able to click a pending desk and create a booking when the desk is available,
- Users should not be able to book a occupied (red) desk, instead it should show the booked users name.

https://gyazo.com/08476d186cf4c69892aacb4ef359f455

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/2ba005a8-4678-41e0-80f7-ffb39643d755)

**Comment by MrYuion** [comment]
Pushed a fix.

**Comment by jeremyw24** [comment]
@MrYuion I can not not click a pending desk, per expected outcomes:

Expected Behaviour:

**Users should be able to click a pending desk and create a booking when the desk is available,**
Users should not be able to book a occupied (red) desk, instead it should show the booked users name.

**Comment by MrYuion** [comment]
Hmm... that's what the logic was doing before.
I'm guessing it let you book as the room was actually free in the that the API doesn't return a booking for that desk but the driver data is stale setting the map as pending.
