### ISSUE TITLE
WPA -> Mobile -> Book Desk -> Add Desk no Modal

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#293]
When in responsive/mobile mode, and user clicks the add desk button in desk booking, the screen goes grey but the add desk modal does not display.

Expected Behaviour:
- Desk listing modal should be displayed.

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/c605c479-9f16-4f20-b18d-5d3a3b470ce2)

**Comment by MrYuion** [comment]
Pushed a fix.
