### ISSUE TITLE
Map Kiosk -> Cant Book Room

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#302]
Can not book rooms from map kiosk:

Request URL: https://gsa.placeos.run/api/staff/v1/events

```
"Not Found\n{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"Resource could not be discovered.\",\"innerError\":{\"date\":\"2023-01-23T21:49:47\",\"request-id\":\"f5dcee2f-de1f-4075-8d0d-01ff42162038\",\"client-request-id\":\"f5dcee2f-de1f-4075-8d0d-01ff42162038\"}}}"
```

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/5ee07f3a-d9b5-4a59-8ce3-c47e3450130b)

**Comment by MrYuion** [comment]
Hmm... can I at least get the request body? That error doesn't really tell me anything.

**Comment by MrYuion** [comment]
Seems to be working fine for me.
