### ISSUE TITLE
WPA -> Editing Room Booking

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#307]
When editing a room booking, users are able to change the title, time, date etc. but when changing the room it returns a object object error and you can not save.

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/51cb62b4-0b68-4b94-9aec-b4b195c217e7)

**Comment by MrYuion** [comment]
Seems like a backend issue to me.

**Comment by jeremyw24** [comment]
@stakach
