### ISSUE TITLE
ngx-staff-app>Google Analytics: page navigation is not captured

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#4]
Transferred from Jira: https://acaprojects.atlassian.net/browse/PTT-49

When Google Analytics was deployed for kpmg-staff-app (a recent fork of ngx-staff-app which does not have many customisations), url navigation is not captured past the /#/

For example, we want to see when the user navigates to /staff/#/explore and /staff/#/book and /staff/#/book/room.
But we can only see /staff:
![image](https://user-images.githubusercontent.com/4019090/99203258-17d9da00-2806-11eb-8491-41624b85fbd8.png)
![image](https://user-images.githubusercontent.com/4019090/99203263-1c05f780-2806-11eb-821a-7df30646e546.png)

What changes need to be made to ngx-staff-app OR google analytics settings to allow the user URL navigation (after /#/) to be recorded?

**Comment by MrYuion** [comment]
@w-le, is this still needed?

**Comment by w-le** [comment]
yes it would give really useful indicators for which parts of the app are used most and least.

So stilll very highly desirable, and eventually needed when a client inevitably asks about it.

But not urgent at all

**Comment by w-le** [comment]
i'll leave this unassigned because it's the kind of task that other fe programmers should be able to pick up (i.e. it doesn't have to be alex)

**Comment by w-le** [comment]
cool is it closed cause it's implemented or cause it's rejected?

**Comment by w-le** [comment]
oh i see now that i was "closed this as completed)"
that's awesome, thanks

**Comment by w-le** [comment]
hey @MrYuion which commit/PR adds the functionality? Just curious as I like to learn how things work.
