### ISSUE TITLE
Concierge will error on certain bookings and won't display any bookings afterwards

### ISSUE THREAD

**Issue by pkheav** [PlaceOS/user-interfaces#40]
[APP][APP] 0e44214 | Built: 14th Apr 2021, 5:32AM

Branch: https://github.com/PlaceOS/user-interfaces/tree/build/concierge%2Fdev
Commit hash: a3f7af6

**Describe the bug**
In the day view, upon receiving this response https://gist.github.com/pkheav/baa3977282da2f12c147ecdb811961a1 from the `events` endpoint, the frontend will error with this and not show any bookings.

> errorhandler.js:22 TypeError: Cannot read property 'zones' of undefined
    at events-state.service.ts:412
    at Array.find (<anonymous>)
    at events-state.service.ts:412
    at Array.find (<anonymous>)
    at events-state.service.ts:412
    at Array.filter (<anonymous>)
    at e.filterEvents (events-state.service.ts:403)
    at o.project (events-state.service.ts:110)
    at o._next (map.js:29)
    at o.next (Subscriber.js:49)

Afterwards, navigating to any other day with valid/working bookings, no bookings are still shown so the concierge will stop showing any bookings at all upon getting this error.

**Expected behavior**
The concierge should show the bookings but if there are malformed bookings which cause the frontend to error, that should not cause the frontend to stop showing any bookings afterwards especially if those bookings work fine normally.

**Comment by pkheav** [comment]
Looks like https://github.com/PlaceOS/user-interfaces/commit/5670858876cf1b11b9b75d24a295471f8e4e01e6 solved the issue of the frontend erroring and not showing any bookings afterwards but the concierge appears to be hiding bookings that I'm assuming would of caused an error originally.

Here is the response from the `events` endpoint causing it https://gist.github.com/pkheav/0bd9fa6987893b12c1002f82d6c415df.

There are only 2 bookings. The first one is not shown so I'm assuming that is the one with issues and the second one shows up fine.

The only differences I can see are:
1. `Microsoft Teams Meeting` in the location field of the first booking which isn't in the second booking.
2. Room attendee has `resource: true` in the first booking but the second booking has `resource: false`

**Comment by MrYuion** [comment]
The issue is most likely backend in that the room has been set up correctly preventing the frontend from retrieving it.

**Comment by jeremyw24** [comment]
@pkheav can you confirm if this issue still exists?

**Comment by pkheav** [comment]
I've went through a month of bookings on a previously affected client and I could see all bookings being returned by the backend on the frontend. There wasn't too many bookings though but I will close this ticket for now and reopen if I see the issue again.
