### ISSUE TITLE
Concierge > Day View > Create Room Booking > Add @place.tech attendee: Visitor expected checkbox does not update correct value in attendee object 

### ISSUE THREAD

**Issue by pkheav** [PlaceOS/user-interfaces#45]
[APP][APP] f2c1e75 | Built: Today at 12:41AM

Adding an external attendee which defaults to having the checkbox `Visitor Expected` ticked
![image](https://user-images.githubusercontent.com/18463731/118627778-eac1b080-b7c3-11eb-855d-9a898a2859f7.png)

The frontend sends `visitor_expected: false` in the attendee object in the POST of the body to `api/staff/v1/events`
![image](https://user-images.githubusercontent.com/18463731/118628219-53a92880-b7c4-11eb-9ed1-c25ef783ecfb.png)

**Comment by MrYuion** [comment]
This is not an issue. By default emails that get set with `place.tech` email addresses are treated as internal users.

**Comment by pkheav** [comment]
Ah I see thanks for that @MrYuion , I can see this as being handy for testing but also confusing for anyone who isn't aware of this like I was.

**Comment by w-le** [comment]
Phil: Looks like there's some frontend code where `@place.tech` emails are treated as internal

**Comment by MrYuion** [comment]
The email address is configurable.

**Comment by pkheav** [comment]
how do you customise it @MrYuion ?

**Comment by MrYuion** [comment]
`app.booking.internal_emails` in the settings.
