### ISSUE TITLE
Explore view - potential loop on load

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/user-interfaces#46]
**Describe the bug**
When loading the explore view, there appears to be an intermittent issue that can result in non-terminating behaviour. Cause for this is currently unexplored, but has been observed on a number of system.

**Screenshots**
![F4CD961C-1434-4B8D-8BE2-9A641C5193B8](https://user-images.githubusercontent.com/843652/119060621-e8ef2b80-ba15-11eb-9d16-e21a704e26af.jpeg)

**Desktop (please complete the following information):**
 - OS: iPadOS
 - Browser: Edge

**Smartphone (please complete the following information):**
 - Device: iPad Pro
 - OS: iPadOS 
 - Browser Safari

**Additional context**
Issue is intermittent, but does seem to pop up on many dev systems possibly without expecting bindings, or configured staff API.

**Comment by MrYuion** [comment]
@kimburgess, is this still an issue?

**Comment by kimburgess** [comment]
Unsure what build this is running, but can confirm (just tested) that attempting to load https://templates.demo.place.tech/map-kiosk/#/explore on a 3rd Gen iPad Pro results in a not fun time.

**Comment by MrYuion** [comment]
Hmm... any console errors? Is the user details being loaded?

**Comment by MrYuion** [comment]
Pushed up a fix. Make sure the template UI is running with mocks by adding `?mock=true` to the URL.

**Comment by jeremyw24** [comment]
@kimburgess ready for testing again.
