### ISSUE TITLE
Visitor kiosk checkin is replacing the @ in emails

### ISSUE THREAD

**Issue by pkheav** [PlaceOS/user-interfaces#47]
[APP][APP] 409abfa | Built: 20th May 2021, 7:33AM

Request url is `/api/staff/v1/guests/phil%40place.technology` when it should be `/api/staff/v1/guests/phil@place.technology` which causes the backend to error with a 404.

![image](https://user-images.githubusercontent.com/18463731/119673292-277c5000-be33-11eb-9ab6-de9ef9141d16.png)

**Comment by MrYuion** [comment]
That's URL encoded, `%40` is `@`. You probably should be decoding those parameters.
