### ISSUE TITLE
Workplace template does not included system with booking requests

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/user-interfaces#48]
When creating a new booking, a request is currently made to the `events` endpoint with system details included as a resource.

![6392A68C-8FF7-4727-9F80-8CCB8886AFCC](https://user-images.githubusercontent.com/843652/120172669-a19f4100-c246-11eb-8c0e-d60d50be29af.jpeg)

Looking at the [corresponding model](https://github.com/place-labs/staff-api/blob/759d3ddd50ec7c3cfacd56e1bd18981257ef3ecf/src/models/event.cr#L67-L68) for this, it appears that the system ID should instead be provided as a `system_id` attribute in the event body. @stakach to confirm.

**Comment by MrYuion** [comment]
Hmm... while it's fine for me to fix this, it doesn't allow for handling of multi-system bookings.
