### ISSUE TITLE
Workplace template errors when booking a desk from explore view

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/user-interfaces#49]
When attempting to book a desk from explore view, the following error is hit.

https://github.com/PlaceOS/user-interfaces/blob/81f167ff1753f94903168b07c4e5bf0c0594cca5/libs/bookings/src/lib/desk.service.ts#L44

At no point during this flow is the ability to select a host provided to the user.

**Comment by w-le** [comment]
I happened to test this just now and can confirm that this is still an issue in latest workplace dev  `409f110 | Built: 3rd Jun 2021`

**Comment by MrYuion** [comment]
This should be fixed in the refactor.

**Comment by kimburgess** [comment]
@MrYuion can you provide a little more context on what that means? Is that refactor available, or still WIP?

**Comment by MrYuion** [comment]
I was thinking of a different issue. I've pushed a fix.
