### ISSUE TITLE
Front End Update for FindMe

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#5]
Transferred from Jira: https://acaprojects.atlassian.net/browse/PTT-189

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MrYuion** [comment]
@jeremyw24, not sure what needs to be done for this.
If we're moving to PlaceOS I'm guessing this will be handled on the backend side of things.
