### ISSUE TITLE
workplace/schedule: Clicking on a desk booking makes an invalid request then shows a spinner forever

### ISSUE THREAD

**Issue by w-le** [PlaceOS/user-interfaces#52]
develop branch ` 409f110 | Built: 3rd Jun 2021`
When clicking on a desk booking in Schedule, an invalid request is made, in the format `/api/staff/v1/events/15?calendar=desks` where 15 is the placeos booking id. At the same time there is also a valid request made to /api/staff/v1/bookings/15

Then, the app displays a loading spinner forever like this
![image](https://user-images.githubusercontent.com/10395560/122235300-2a2d0b00-cef0-11eb-9250-8960293ff011.png)

**Comment by MrYuion** [comment]
This should be fixed in the refactor.

**Comment by w-le** [comment]
oh ok so should I use a different build branch? currently using build/workplace/develop

**Comment by MrYuion** [comment]
There isn't a build with the refactor yet. I still need to finish refactoring the main desk booking flow.

**Comment by w-le** [comment]
cool no worries, let me know when it's ready. this particular issue is not super urgent at this stage

**Comment by MrYuion** [comment]
Refactor has been merged into `develop`
