### ISSUE TITLE
[develop] concierge/visitors checkin POST request is incorrect

### ISSUE THREAD

**Issue by w-le** [PlaceOS/user-interfaces#54]
`[APP][APP] 409f110 | Built: 3rd Jun 2021, 8:46AM`

[develop] concierge/visitors checkin POST request is incorrect

currently it posts `/api/staff/v1/events/<event id>/guests/?system_id=<system id>&state=true`

but that needs to be `/api/staff/v1/events/<event id>/guests/<guest email>/checkin?system_id=sys-GAfNtUViWCw&state=true`
so it's missing guest email and `/checkin`

**Comment by jeremyw24** [comment]
@w-le can you please test this fix?

**Comment by w-le** [comment]
looks like the POST URI is missing the guest email:
![image](https://user-images.githubusercontent.com/10395560/127618329-61572d0e-fef1-4d46-b1ce-c33751d62602.png)

I've confirmed that the `event.attendees[]` has the guest email in it and is a valid, normal email string
![image](https://user-images.githubusercontent.com/10395560/127618603-473bfbed-940a-49bf-9a60-3b7dc58b04e1.png)

**Comment by MrYuion** [comment]
I've pushed up a fix for that.

**Comment by jeremyw24** [comment]
@w-le another one for testing

**Comment by jeremyw24** [comment]
bump @w-le for testing.

**Comment by jeremyw24** [comment]
bump @w-le
