### ISSUE TITLE
Desk Booking QR Code Generation

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#55]
**Is your feature request related to a problem? Please describe.**
Currently generate QR Codes in a spreadsheet i.e. https://docs.google.com/spreadsheets/d/1BNXPptAlVi18_QXsVZNVrtYzRTuessucTFGM3U1796w/edit?usp=sharing and send to client. Moving forward with SaaS and other things it would be ideal if we could generate/view the desks QR Codes via Concierge.

**Describe the solution you'd like**
Ability to generate, download, view a desks checkin QR Code via Concierge.

**Comment by MrYuion** [comment]
That shouldn't be too hard. I'll look into it when refactoring the Concierge UI.

**Comment by jeremyw24** [comment]
@MrYuion got somewhere I can test this?

**Comment by MrYuion** [comment]
https://templates.demo.place.tech/concierge/#/desks/manage?zone_ids=bld-01_lvl-11
Might need to wait for the next build though.
