### ISSUE TITLE
Ability to Import Menu into Concierge

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#56]
Provide a CSV Template that can be loaded with relevant menu data and imported back via Concierge to populate the menu,

**Comment by jeremyw24** [comment]
@MrYuion got somewhere I can test this one too?

**Comment by MrYuion** [comment]
You should be able to test it here:
https://templates.demo.place.tech/concierge/#/catering/menu?zone_ids=bld-01_lvl-10

**Comment by jeremyw24** [comment]
Cool, works.
