### ISSUE TITLE
adding new driver to system requires refresh

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#62]
**Describe the bug**
When you add a new driver to a system you need to refresh the page or navigate away to another system and back before the driver appears.

**To Reproduce**
1. Add new driver.

**Expected behavior**
Driver should appear without refresh.

**Screenshots**

https://user-images.githubusercontent.com/4019090/126316599-d1c461e9-f0e6-4f7e-b346-172a14d4a04e.mov

**Comment by MrYuion** [comment]
@jeremyw24, should this be on the backoffice repo?

**Comment by jeremyw24** [comment]
@MrYuion Yeah, my bad.

**Comment by jeremyw24** [comment]
Tested, Fixed.
