### ISSUE TITLE
input validation for phone numbers

### ISSUE THREAD

**Issue by w-le** [PlaceOS/user-interfaces#64]
Several apps allow inputting of phone numbers (e.g. when adding a new Guest).

On the backend they are stored as strings as they may include `+ ( ) - ` and spaces.

Generally the phone numbers will not include anything else though.

Can we improve the frontend validation for all Phone Number input fields to only allow:
0-9, `+ (  ) - ` and spaces.

**Comment by jeremyw24** [comment]
@MrYuion  This issue still persists. Was able to enter all valid characters into phone field.

**Comment by MrYuion** [comment]
All characters are valid in telephone input fields.
Limiting the input is hacky.
On mobile/touch devices it should only show the numpad for input.

**Comment by jeremyw24** [comment]
Tested on mobile and working as expected.
