### ISSUE TITLE
Explore component > Area Labels: Default to rendering labels in the centre of the area

### ISSUE THREAD

**Issue by w-le** [PlaceOS/user-interfaces#67]
Explore component > Area Labels: Default to rendering labels in the centre of the area

Allow the default to be **optionally overridden** when the admin manually sets `zone.metadata.map_regions.properties.label_location`

Allow the label to optionally be HIDDEN when the admin manually sets `zone.metadata.map_regions.properties.hide_label`: true

**Comment by w-le** [comment]
alex added it in 1aa1f7aaa0f2433f0478b69f8115dce058768775

untested e2e

**Comment by jeremyw24** [comment]
tested and resolved
