### ISSUE TITLE
workplace/dashboard > Your Bookings: Clicking on a booking tile does nothing, but should show the booking details (/schedule/view) 

### ISSUE THREAD

**Issue by w-le** [PlaceOS/user-interfaces#86]
workplace/dashboard > Your Bookings: Clicking on a booking tile does nothing, but should show the booking details (/schedule/view) 

![image](https://user-images.githubusercontent.com/10395560/140498197-ab994dc4-a1e5-42a2-b366-33429b838412.png)

**Comment by MrYuion** [comment]
This is not an issue for user-interfaces due to the Phase 2 UX changes.

**Comment by MrYuion** [comment]
I have changed this for the clients version though.

**Comment by w-le** [comment]
awesome thanks
