### ISSUE TITLE
workplace/dashboard > Your Bookings: Clicking on the Location link tries to display a modal of the room pinned in the map, but this fails.

### ISSUE THREAD

**Issue by w-le** [PlaceOS/user-interfaces#87]
workplace/dashboard > Your Bookings: Clicking on the Location link tries to display a modal of the room pinned in the map, but this fails.
Instead, can you make it move to /explore and pin the room there?

![image](https://user-images.githubusercontent.com/10395560/140498407-94f3606e-5d92-4b91-8c09-a630abfbd555.png)

**Comment by MrYuion** [comment]
That's like likely due to the room not matching one of the "available" level zones.

**Comment by w-le** [comment]
hmm in this case the system's zones and map_id config are definitely correct though, as we can locate it from the explore page fine:
![image](https://user-images.githubusercontent.com/10395560/140499036-333fecfa-2d1a-48e3-855b-3e7c3ea755a5.png)

**Comment by w-le** [comment]
btw you can do this on monday as opposed to now if you prefer

**Comment by MrYuion** [comment]
Any console errors?

**Comment by w-le** [comment]
not really, there is this on app load (not sure if related):
![image](https://user-images.githubusercontent.com/10395560/140499389-b73e01fa-cd8e-41b4-9394-6a65b8a790b7.png)

and not console output at all on booking Location link click from /dashboard

**Comment by w-le** [comment]
cool looks like your recent commit in the client repo resolved the issue. tested OK in build `2efcab6`
