### ISSUE TITLE
Enrolment App: Support Uploads

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#91]
Objective: Enable ability to upload files via the Enrolment App which would then be visible via the Concierge against the visitor record.

This would potentially include identification documentation such as a drivers license or national ID Card.

This will form part of an a visitor approval process, that will block the visitor from attending site until the ID is uploaded and validated.

**Comment by MrYuion** [comment]
Currently there isn't an enrolment app in the templates.
Is that something I should add?

**Comment by jeremyw24** [comment]
oh really! yeah we should add it as part of the template, just grab the pwcme one and make it placeos-ish.

**Comment by MrYuion** [comment]
Okay.
