### ISSUE TITLE
Concierge: Visitors Approval Gates

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/user-interfaces#92]
Objective: Provide an approval gate to visitor workflow, once a visitor is invited they will be provided the Enrolment App Link there they will need to complete the form and/or upload documentation.

Concierge will show this visitor record as pending approval until all required items are met and concierge has reviewed the visitor and approved. 

Concierge will have ability to view any uploaded files and provide approval. Notification should be provided to the host and visitor that the visit has been approved.

**Comment by MrYuion** [comment]
@jeremyw24, for the notifications that would likely be a backend thing.
